# -*- coding: utf-8 -*-
"""AutoML_forms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LpWOY446e3tYJhqhG44WHO53ztqgK1mZ
"""

# !pip install flask_wtf

from flask_wtf import FlaskForm

from wtforms import  StringField,SubmitField,SelectField

# Validators
from wtforms.validators import DataRequired,Length

class UrlForm(FlaskForm):
  problem_types_values = ['Classification','Regression']
  url = StringField('Paste Url', validators=[DataRequired(),Length(min=15)])
  problem_type = SelectField('Problem Type', choices=problem_types_values)
  submit = SubmitField('Get Model')